# Generated by Django 4.2 on 2023-07-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="cake",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, verbose_name="Вес"
            ),
        ),
    ]
