# Generated by Django 4.2 on 2023-07-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_alter_cake_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inscription",
                    models.CharField(max_length=200, verbose_name="Надпись"),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                ("order_at", models.DateTimeField(verbose_name="Доставка")),
                (
                    "berry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.berry",
                        verbose_name="Ягоды",
                    ),
                ),
                (
                    "cake_catalog",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.cake",
                        verbose_name="Торт",
                    ),
                ),
                (
                    "cake_form",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.cakelevel",
                        verbose_name="Форма",
                    ),
                ),
                (
                    "cake_level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders_lv",
                        to="main_app.cakelevel",
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="main_app.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "decor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.decor",
                        verbose_name="Декор",
                    ),
                ),
                (
                    "topping",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.topping",
                        verbose_name="Топпинг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
