# Generated by Django 4.2 on 2023-07-23 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_ordercake"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercake",
            name="berry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.berry",
                verbose_name="Ягоды",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="cake_catalog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.cake",
                verbose_name="Торт",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="cake_form",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.cakeform",
                verbose_name="Форма",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="cake_level",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.cakelevel",
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="decor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.decor",
                verbose_name="Декор",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="topping",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.topping",
                verbose_name="Топпинг",
            ),
        ),
    ]
