# Generated by Django 4.2 on 2023-07-23 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "main_app",
            "0006_alter_ordercake_berry_alter_ordercake_cake_catalog_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordercake",
            name="order_at",
        ),
        migrations.AddField(
            model_name="ordercake",
            name="order_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Доставка"
            ),
        ),
        migrations.AddField(
            model_name="ordercake",
            name="order_time",
            field=models.CharField(
                choices=[("AM", "11:00 - 15:00"), ("PM", "15:00 - 19:00")],
                default="PM",
                max_length=15,
                verbose_name="Время доставки",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="berry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.berry",
                verbose_name="Ягоды",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="cake_catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.cake",
                verbose_name="Торт",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="cake_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.cakeform",
                verbose_name="Форма",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="cake_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.cakelevel",
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="decor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.decor",
                verbose_name="Декор",
            ),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="inscription",
            field=models.CharField(blank=True, max_length=200, verbose_name="Надпись"),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="topping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="main_app.topping",
                verbose_name="Топпинг",
            ),
        ),
    ]
