# Generated by Django 4.2 on 2023-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_remove_ordercake_order_at_ordercake_order_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordercake",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="ordercake",
            name="inscription",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Надпись"
            ),
        ),
    ]
