# Generated by Django 4.2 on 2023-07-24 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_ordercake_comment_alter_ordercake_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercake',
            name='adress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='ordercake',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='ordercake',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='Телефон'),
        ),
    ]
